#!/bin/bash
#for linux
#掃描同網段活動主機及其開放端口
#scan living host and port
#the firt work in github
#創建於2023/5/6
#create by RedCollaredDove



read -p "input the ip adress-->"  ip_adress
nmap -sn $ip_adress/24 | grep 'for' | awk '{print $5}' > living_host.txt


cat living_host.txt
echo > t1.txt
echo -e "\n"
echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> t1.txt


for line in $(cat living_host.txt)
        do
                        #echo $line
                the_last2_ip=${line: -2}
                        #echo $the_last2_ip
                the_last3_ip=${line: -3}
                        #echo $the_last3_ip


                if [[ $the_last2_ip != ".1" ]] && [[ $the_last2_ip != ".2" ]] && [[ $the_last3_ip != "254" ]]&& 
                        [[ $line != "$ip_adress" ]];then


                        echo -e "++++++++++++++++++++"
                        echo "scanning $line"
                        echo -e "scan port of $line\n\n" >> t1.txt
                        nmap -A -p- $line >> t1.txt
                        echo "done"
                        echo -e "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> t1.txt

                fi

        done
echo "+++++++++++++++++++"















